### ISSUE TITLE
BSAPI-7: Creating a 5 star scale rating for a book with a timestamp

### ISSUE THREAD

**Issue by airiz04** [Software-Engineering-1-Group-13/Bookstore-API#13]
### Summary
Provide a way to rate a book out of 5 stars, including a timestamp.

### Rationale
- **Motivation**: Users will want to rate books they've read on a 5 star scale.
- **Functionality**: By getting the the user and book ID, along with the number of stars, the user will be able to leave a rating on any book.
- **Impact**: Will impact the ratings and books tables, and perhaps other services that utilize book data.

### Acceptance Criteria
- POST /ratings/books
- Paramaters sent: Rating, User Id, Book Id
- Successful response: New rating is

**Comment by IvanoskiHarmonia** [comment]
Please re-commit this code with spotlessApply applied to it. so you can pass the spotlessCheck that we have.
