### ISSUE TITLE
BSAPI-8: Create a User with username, password and optional fields (Profile Management - 1)

### ISSUE THREAD

**Issue by dannysusername** [Software-Engineering-1-Group-13/Bookstore-API#16]
**Feature Overview**
Create user profile functionality with various fields

**Summary**
Create a User with username, password and optional fields (name, email
address, home address

**Rationale**
- **Motivation**: Users don't want to re enter the same information each time they order books
- **Functionality**: By getting the users information and saving it there profile will be created and saved on the database.
- **Impact**: Will impact profile tables and other services that include profile data

**Acceptance Criteria**
- List the specific conditions that must be met for this feature to be considered complete. This might include:
- The user can enter a user name which will be stored on a database 
- The user can enter a first name and last name which will be stored on a database 
- The user can enter a password which will be stored on a database 
- The user can enter an address which will be stored on a database 
- The user will click on a save button to persist the info on a database 
- The users will receive a success message. 

**Acceptance Test Cases:**
1. Go to the create profile screen, fill out a username and password (must adhere to security standards), and click save. 
2. A confirmation screen will let you know that the account was created. 
3. Verification of the database will show that the account was created.

**Comment by IvanoskiHarmonia** [comment]
Don't forget to set the milestone.
Also don't forget to make the issue title more descriptive `Profile Creation` is way too generic.
