### ISSUE TITLE
BSAPI-20: Retrieve subtotal price of items in shopping cart (Cart - 1)

### ISSUE THREAD

**Issue by nimperatori** [Software-Engineering-1-Group-13/Bookstore-API#33]
### Summary
Implement a functionality in the Bookstore API that allows users to retrieve the subtotal price of all items in their shopping cart.

### Rationale
- **Motivation**: Users need an overview of their potential expenses before making a purchase.
- **Functionality**: By providing the subtotal of items, users can make informed decisions about their purchases.
- **Impact**: This will affect the shopping cart endpoint and potentially interact with the book prices in the database.

### Acceptance Criteria
- Endpoint to fetch the subtotal for a user based on User Id.
- Should return a calculated subtotal based on current book prices.

### Acceptance Test Cases:
- Test Case 1: If a valid User Id is provided, then the correct subtotal amount is returned.
- Test Case 2: If an invalid User Id is given, then an appropriate error message is returned.

### Additional Information
Ensure the subtotal considers any discounts or promotions currently active.

**Comment by IvanoskiHarmonia** [comment]
Sorry but not the proper naming, it should describe what you are implementing not what you are going to add to the repo.
