### ISSUE TITLE
BSAPI-29: Retrieve average rating of a book

### ISSUE THREAD

**Issue by airiz04** [Software-Engineering-1-Group-13/Bookstore-API#64]
### Summary
Provide a way to retrieve the average rating of a book

### Rationale
- **Motivation**: The user may want to see the average rating of a book before they purchase.
- **Functionality**: By providing the book ID, a decimal containing the average rating will be returned.
- **Impact**: Affects the book and rating classes.

### Acceptance Criteria
- New endpoint: GET /book/{bookID}/avgRating
- Parameters Sent: Book Id
- Successful Response: HTTP 200 OK

**Comment by IvanoskiHarmonia** [comment]
You can actually use the #28 to help you solve this. it is very similar.
